### ISSUE TITLE
This repo doesn't meet the "durable ownership minimums" for Microsoft compliance

### ISSUE THREAD

**Issue by jdubois** [microsoft/ImagineCup#39]
I've been pinged as this repo doesn't meet the "durable ownership minimums" for Microsoft compliance.
Please add another owner to this repo to meet those requirements!
I'll check this in 2 weeks, if the requirements are not met, I'll add myself as an owner, and archive the repo.

**Comment by damolin** [comment]
Closing issue, there are two owners already for this repo since 10/13, @jdubois feel free to reach me directly via Microsoft teams.

**Comment by jdubois** [comment]
Awesome, thank you!
